language: python
sudo: false
addons:
  apt:
    packages:
      - libatlas-dev
      - liblapack-dev
      - gfortran
python:
  - '3.6'
  - '2.7'
install:
- travis_wait pip install -e .
before_script:
  - 
script: nosetests
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: MbSaeuitkVTZqxa0PJ3RcR1aMf+B/sMbcx2sWOo9xfLlRFDFpYWJZ0EfXWEhrVu2YWXpBsasgunTDWSi0jNcZMH92MzOC+UTVYr45LO5sy6hm4iSiAgm/DPgYWdjP0SFKr7eL/HWPS+gHvgkXL1upleX21O358bxaezoasuKFvs=
  on:
    all_branches: true
    python: 2.7
    tags: true
    repo: mdshw5/fastqp
