language: python
sudo: false
addons:
  apt:
    packages:
      - libatlas-dev
      - libatlas
      - liblapack-dev
      - liblapack
      - gfortran
python:
- '3.4'
- '2.7'
install:
- travis_wait pip install -e .
script: nosetests
deploy:
  provider: pypi
  user: mdshw5
  password:
    secure: VvLKelsgBK2xPqvGRceFhgV7WInXdxfFFkvvUZrT6GyVcoIJtsmFZ1uvUcwvtxPMmNcLC/9MpoeNaIvuXH7PgYUMRG8xkzev/ldS7hzmeXCLxKzixGvAd07lzXcNT+u6JqpOM6HGwdhQpEmeZzK2gbRHJFJIqYyWE5PjewsEbSI=
  on:
    all_branches: true
    python: 2.7
    tags: true
    repo: mdshw5/fastqp
